services:
  server:
    container_name: server
    build:
      context: ./docker/server
      dockerfile: dockerfile
      args:
        - UID=1000
        - GID=1000
        - USERGROUP=server
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html:rw
    networks:
      - localnet
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    build:
      context: ./docker/mysql
      dockerfile: dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=framework
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
    networks:
      - localnet
    # docker exec mysql /dumpdb # create dump db
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=rootpassword
    depends_on:
      - mysql
    networks:
      - localnet

networks:
  localnet:
    name: localnet
